// Typed loader for data/activity.json — the build-time, commit-driven proof of
// work generated by scripts/build-activity-feed.mjs. Mirrors lib/status.ts: a
// single import surface so the status page never invents data. If the JSON is
// regenerated empty (no repos / no history), every number here is honestly 0.
import data from "@/data/activity.json";

export type CommitType =
  | "feat" | "fix" | "docs" | "chore" | "refactor"
  | "test" | "perf" | "build" | "ci" | "style" | "revert" | "other";

export type ActivityEntry = {
  date: string;       // YYYY-MM-DD
  iso: string;        // full ISO-8601 (with original tz offset)
  subject: string;    // scrubbed commit subject — no emails, no secrets
  repo: string;       // "web" | "core"
  repoLabel: string;  // human label, e.g. "atmosphere-core"
  type: CommitType;
};

export type RepoMeta = {
  key: string;
  label: string;
  present: boolean;
  commits: number;
  newestAt: string | null;
};

export type Rollups = {
  totalCommits: number;
  last7Days: number;
  last30Days: number;
  featuresShipped: number;
  byType: Partial<Record<CommitType, number>>;
};

export type Activity = {
  generatedAt: string;
  repos: RepoMeta[];
  rollups: Rollups;
  feed: ActivityEntry[];
};

const activity = data as Activity;

export const GENERATED_AT = activity.generatedAt;
export const REPOS = activity.repos;
export const ROLLUPS = activity.rollups;
export const FEED = activity.feed;

// Human-friendly labels + accent colors per conventional-commit type. Kept here
// (presentation) rather than in the build script (data) so the artifact stays
// purely factual. "feat" reuses the brand signal — features are the headline.
export const TYPE_META: Record<CommitType, { label: string; color: string }> = {
  feat: { label: "Feature", color: "var(--color-signal)" },
  fix: { label: "Fix", color: "#86c5ff" },
  perf: { label: "Perf", color: "#7fe0c4" },
  refactor: { label: "Refactor", color: "#c9a24b" },
  docs: { label: "Docs", color: "#9aa6b5" },
  test: { label: "Test", color: "#9aa6b5" },
  build: { label: "Build", color: "#9aa6b5" },
  ci: { label: "CI", color: "#9aa6b5" },
  chore: { label: "Chore", color: "#5b6675" },
  style: { label: "Style", color: "#5b6675" },
  revert: { label: "Revert", color: "#e07f7f" },
  other: { label: "Commit", color: "#5b6675" },
};

export function typeMeta(t: string) {
  return TYPE_META[(t as CommitType)] ?? TYPE_META.other;
}
