// Typed loader for data/activity.json — the build-time, commit-driven proof of
// work generated by scripts/build-activity-feed.mjs. Mirrors lib/status.ts: a
// single import surface so the status page never invents data. If the JSON is
// regenerated empty (no repos / no history), every number here is honestly 0.
import data from "@/data/activity.json";

export type CommitType =
  | "feat" | "fix" | "docs" | "chore" | "refactor"
  | "test" | "perf" | "build" | "ci" | "style" | "revert" | "other";

export type ActivityEntry = {
  date: string;       // YYYY-MM-DD
  iso: string;        // full ISO-8601 (with original tz offset)
  subject: string;    // scrubbed commit subject — no emails, no secrets
  repo: string;       // "web" | "core"
  repoLabel: string;  // human label, e.g. "atmosphere-core"
  type: CommitType;
  hash: string;       // short sha (%h) for display — no PII, no secret
  commitUrl: string;  // GitHub commit URL (may be "" if repoUrl/sha absent)
};

export type RepoMeta = {
  key: string;
  label: string;
  present: boolean;
  commits: number;
  newestAt: string | null;
  repoUrl: string;    // where this repo lives on GitHub (public at launch)
};

export type Rollups = {
  totalCommits: number;
  last7Days: number;
  last30Days: number;
  featuresShipped: number;
  activeDays: number;
  byType: Partial<Record<CommitType, number>>;
};

// A single calendar date's worth of commits from the rendered slice. Same data
// as FEED, reorganised by the build script — never invented here.
export type FeedDay = {
  date: string;       // YYYY-MM-DD
  count: number;      // commits landed that day (within the rendered slice)
  byType: Partial<Record<CommitType, number>>;
  commits: ActivityEntry[];
};

export type Activity = {
  generatedAt: string;
  repos: RepoMeta[];
  rollups: Rollups;
  feed: ActivityEntry[];
  feedByDate: FeedDay[];
};

const activity = data as Activity;

export const GENERATED_AT = activity.generatedAt;
export const REPOS = activity.repos;
export const ROLLUPS = activity.rollups;
export const FEED = activity.feed;
// The same commits as FEED, grouped by date (newest date first). Falls back to
// an empty array if an older activity.json (pre-grouping) is loaded.
export const FEED_BY_DATE: FeedDay[] = activity.feedByDate ?? [];

// Human-friendly labels + accent colors per conventional-commit type. Kept here
// (presentation) rather than in the build script (data) so the artifact stays
// purely factual. "feat" reuses the brand signal — features are the headline.
export const TYPE_META: Record<CommitType, { label: string; color: string }> = {
  feat: { label: "Feature", color: "var(--color-signal)" },
  fix: { label: "Fix", color: "#86c5ff" },
  perf: { label: "Perf", color: "#7fe0c4" },
  refactor: { label: "Refactor", color: "#c9a24b" },
  docs: { label: "Docs", color: "#9aa6b5" },
  test: { label: "Test", color: "#9aa6b5" },
  build: { label: "Build", color: "#9aa6b5" },
  ci: { label: "CI", color: "#9aa6b5" },
  chore: { label: "Chore", color: "#5b6675" },
  style: { label: "Style", color: "#5b6675" },
  revert: { label: "Revert", color: "#e07f7f" },
  other: { label: "Commit", color: "#5b6675" },
};

export function typeMeta(t: string) {
  return TYPE_META[(t as CommitType)] ?? TYPE_META.other;
}

// ── Public product repos (the "View on GitHub" buttons) ──────────────────────
// These are the repos we point the public at. They are intentionally listed by
// hand (not derived from the activity feed) because the feed is built from the
// LOCAL working copies (efficientlabs-web + atmosphere-core), whereas these are
// the product-facing GitHub repos we want visitors to be able to open.
//
// HONESTY: every one of these 404s until we flip the repo public at launch. We
// say so on the page rather than hiding the buttons — a dead link that we label
// "public at launch" is more honest than pretending the code isn't there.
export const GITHUB_ORG = "EfficientLabs-ai";

export type PublicRepo = { name: string; url: string; blurb: string };

export const PUBLIC_REPOS: PublicRepo[] = [
  {
    name: "TheAtmosphere",
    url: `https://github.com/${GITHUB_ORG}/TheAtmosphere`,
    blurb: "The sovereign P2P mesh + agent runtime.",
  },
  {
    name: "StratosAgent",
    url: `https://github.com/${GITHUB_ORG}/StratosAgent`,
    blurb: "The local-first, model-agnostic agent.",
  },
  {
    name: "atmosphere-core",
    url: `https://github.com/${GITHUB_ORG}/atmosphere-core`,
    blurb: "Core libraries — the engine room.",
  },
];
